flask_app/models.py
from flask_login import UserMixin
from .extensions import db

class User(db.Document, UserMixin):
    username = db.StringField(required=True, unique=True)
    email = db.StringField(required=True, unique=True)
    password = db.StringField(required=True)

class Review(db.Document):
    commenter = db.ReferenceField(User, required=True)
    album_name = db.StringField(required=True)
    review = db.StringField(required=True, min_length=5, max_length=500)

flask_app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, PasswordField
from wtforms.validators import InputRequired, Length, Email, EqualTo, ValidationError
from .models import User

class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[InputRequired(), Length(min=1, max=30)])
    email = StringField('Email', validators=[InputRequired(), Email()])
    password = PasswordField('Password', validators=[InputRequired()])
    confirm_password = PasswordField('Confirm Password', validators=[InputRequired(), EqualTo('password')])
    submit = SubmitField('Sign Up')

    def validate_username(self, username):
        user = User.objects(username=username.data).first()
        if user:
            raise ValidationError('Username is taken.')

    def validate_email(self, email):
        user = User.objects(email=email.data).first()
        if user:
            raise ValidationError('Email is already registered.')

class LoginForm(FlaskForm):
    username = StringField('Username', validators=[InputRequired(), Length(min=1, max=30)])
    password = PasswordField('Password', validators=[InputRequired()])
    submit = SubmitField('Login')

class SearchForm(FlaskForm):
    search_query = StringField('Query', validators=[InputRequired(), Length(min=1, max=100)])
    submit = SubmitField('Search')

class SearchNew(FlaskForm):
    search_query = StringField('Query', validators=[InputRequired(), Length(min=1, max=100)])
    submit = SubmitField('Search')

class ReviewForm(FlaskForm):
    text = TextAreaField('Comment', validators=[InputRequired(), Length(min=5, max=500)])
    submit = SubmitField('Enter Comment')

flask_app/__init__.py
from flask import Flask
from .extensions import db, bcrypt, login_manager

def create_app():
    app = Flask(__name__)
    app.config.from_pyfile("config.py")

    db.init_app(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)

    from .routes import main
    app.register_blueprint(main)
    from .routes import searchy
    app.register_blueprint(searchy)

    from .models import User
    login_manager.login_view = "main.login"
    login_manager.login_message_category = "info"

    @login_manager.user_loader
    def load_user(user_id):
        return User.objects(pk=user_id).first()

    return app

flask_app/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from flask_login import login_user, logout_user, login_required, current_user
from .models import User, Review
from .forms import RegistrationForm, LoginForm, SearchForm, ReviewForm
from . import bcrypt, db
from .lastfm_client import LastFmClient
from .config import LASTFM_API_KEY
lastfm_client = LastFmClient(api_key=LASTFM_API_KEY)

main = Blueprint('main', __name__)


@main.route('/')
@main.route('/home')
def home():
    print("User authenticated:", current_user.is_authenticated)
    if current_user.is_authenticated:
        top_albums = lastfm_client.get_top_albums()
        return render_template('home.html', title='Home', albums=top_albums)
    return render_template('home.html', title='Home')


@main.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_pw = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_pw)
        user.save()
        flash('Your account has been created!', 'success')
        return redirect(url_for('main.login'))
    return render_template('register.html', title='Register', form=form)

@main.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.objects(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=True)
            return redirect(url_for('main.home'))
        else:
            flash('Login unsuccessful. Check username and password.', 'danger')
    return render_template('login.html', title='Login', form=form)

@main.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.home'))




searchy = Blueprint('searchy', __name__)

@searchy.route('/search', methods=['GET', 'POST'])
@login_required
def search():
    form = SearchForm()
    results = []
    if form.validate_on_submit():
        query = form.search_query.data
        results = lastfm_client.search_album(query)
    return render_template('search_results.html', title='Search Results', form=form, results=results)

@searchy.route('/searchar', methods=['GET', 'POST'])
@login_required
def searchar():
    form = SearchForm()
    results = []
    if form.validate_on_submit():
        query = form.search_query.data
        results = lastfm_client.search_art(query)
    return render_template('searchartist.html', title='Search Results', form=form, results=results)

flask_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }} - Music App</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
</head>
<body>
    <nav>
        <a href="{{ url_for('main.home') }}">Home</a>
        {% if current_user.is_authenticated %}
            <a href="{{ url_for('searchy.search') }}">Search Tracks</a>
            <a href="{{ url_for('searchy.searchar') }}">Search Artists</a>
            <a href="{{ url_for('main.logout') }}">Logout</a>
        {% else %}
            <a href="{{ url_for('main.login') }}">Login</a>
            <a href="{{ url_for('main.register') }}">Register</a>
        {% endif %}
    </nav>
    <div>
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <p class="{{ category }}">{{ message }}</p>
            {% endfor %}
        {% endif %}
        {% endwith %}
        {% block content %}{% endblock %}
    </div>
</body>
</html>

flask_app/templates/home.html
{% extends "base.html" %}

{% block content %}
    <h1>Welcome to Abhi's/Ankit's Music Search App!</h1>
    {% if albums %}
        <h2>Current Top Tracks</h2>
        <ul>
            {% for album in albums %}
                <li>
                    <strong>{{ album.name }}</strong> by {{ album.artist.name }}<br>
                    <a href="{{ album.url }}" target="_blank">Preview</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Please register or log in to use the site.</p>
    {% endif %}
{% endblock %}

flask_app/templates/login.html
{% extends "base.html" %}
{% block content %}
<h1>Login</h1>
<form method="POST">
    {{ form.hidden_tag() }}
    {{ form.username.label }} {{ form.username() }}<br>
    {{ form.password.label }} {{ form.password() }}<br>
    {{ form.submit() }}
</form>
{% endblock %}

flask_app/templates/register.html
{% extends "base.html" %}
{% block content %}
<h1>Register</h1>
<form method="POST">
    {{ form.hidden_tag() }}
    {{ form.username.label }} {{ form.username() }}<br>
    {{ form.email.label }} {{ form.email() }}<br>
    {{ form.password.label }} {{ form.password() }}<br>
    {{ form.confirm_password.label }} {{ form.confirm_password() }}<br>
    {{ form.submit() }}
</form>
{% endblock %}

flask_app/templates/search_results.html
{% extends "base.html" %}

{% block content %}
    <h1>Search Results</h1>
    <form method="post">
        {{ form.hidden_tag() }}
        {{ form.search_query.label }} {{ form.search_query(size=20) }}
        {{ form.submit() }}
    </form>
    <br>
    {% if results %}
        <h2>Albums Found</h2>
        <ul>
            {% for album in results %}
                <li>
                    <strong>{{ album.name }}</strong> by {{ album.artist}}<br>
                    <a href="{{ album.url }}" target="_blank">Preview</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No tracks found for the search query.</p>
    {% endif %}
{% endblock %}

flask_app/templates/searchartist.html
{% extends "base.html" %}

{% block content %}
    <h1>Search Results</h1>
    <form method="post">
        {{ form.hidden_tag() }}
        {{ form.search_query.label }} {{ form.search_query(size=20) }}
        {{ form.submit() }}
    </form>
    <br>
    {% if results %}
        <h2>Tracks Found</h2>
        <ul>
            {% for album in results %}
                <li>
                    <strong>{{ album.name }}</strong> Listeners {{ album.listeners}}<br>
                    <a href="{{ album.url }}" target="_blank">Preview</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No tracks found for the search query.</p>
    {% endif %}
{% endblock %}